---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: run local python script to create nacl.json
    shell: ./main.py
    register: resultstdout

  - debug: msg="{{ resultstdout.stdout_lines }}"

  - name: register nacl.json content
    shell: cat ./main.py
    register: jsonnaclstdout

  - set_fact:
      from_lookup_with_from_json: "{{ lookup('file','nacl.json') | from_json }}"

  - debug: var=from_lookup_with_from_json

  - name: "INGRESS - Create and associate production DMZ network ACL with DMZ subnets"
    ec2_vpc_nacl:
      vpc_id: vpc-092733162f7694d18
      name: prod-dmz-nacl
      region: "{{ region }}"
      subnets: ['mysubnet3', 'mysubnet2']
      tags:
        CostCode: CC1234
        Project: phoenix
        Description: production DMZ
      ingress:
          # rule no, protocol, allow/deny, cidr, icmp_type, icmp_code, port from, port to
          - [200, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22]
      state: 'present'
    loop: '{{ s3_ranges }}'

  - name: "EGRESS - Create and associate production DMZ network ACL with DMZ subnets"
    ec2_vpc_nacl:
      vpc_id: vpc-092733162f7694d18
      name: SOLOMON
      region: "{{ region }}"
      subnets: ['mysubnet3', 'mysubnet2']
      tags:
        CostCode: CC1234
        Project: phoenix
        Description: production DMZ
      egress:
          - [200, 'all', 'allow', '0.0.0.0/0', null, null, null, null]
      state: 'present'
    loop: '{{ s3_ranges }}'