---
- hosts: localhost
  tasks:

  - name: set facts
    set_fact:
      rule_no: "200"
      json:  "{{lookup('file','data.json')}}"

  - name: debug
    set_fact:
      json_f: "{{ item | combine({ 'rule_no': item.rule_no | int }) }}"
    with_items: "{{ json.egress }}"

  - name: debug
    debug: msg="Value is {{ json_f.rule_no }} == Type is {{ json_f.rule_no | type_debug }}"
